// =================== STATE ===================
// js/state.js — Central application state

const state = {
  files: {},
  folders: new Set(),
  collapsedFolders: new Set(),
  openTabs: [],
  activeTab: null,
  previewTab: null,
  rightPaneTabs: [],
  rightPaneActive: null,
  splitEditor: false,
  currentActivity: 'explorer',
  sidebarVisible: true,
  panelVisible: true,
  previewVisible: false,
  zenMode: false,
  minimapVisible: false,
  mdPreviewVisible: false,
  clipboard: null,
  cutPath: null,
  selectedItems: new Set(), // Multi-selection for files and folders
  lastSelectedItem: null, // For range selection with Shift+click
  acVisible: false,
  acItems: [],
  acIdx: 0,
  cmdPaletteVisible: false,
  cmdIdx: 0,
  problems: {},
  snippets: {},
  settings: {
    fontSize: 14, tabSize: 2, wordWrap: false, autoSave: true,
    lineNumbers: true, minimap: false, theme: 'dark', autoRefreshDelay: 800,
    syntaxHighlight: true, autocomplete: true, emmet: true, linting: true,
  },
  keybindings: {
    newFile: 'Ctrl+N', save: 'Ctrl+S', find: 'Ctrl+F',
    findReplace: 'Ctrl+H', toggleSidebar: 'Ctrl+B',
    quickOpen: 'Ctrl+P', livePreview: 'Ctrl+Shift+L',
    splitEditor: 'Ctrl+\\', zenMode: 'F11',
    commandPalette: 'Ctrl+Shift+P', mdPreview: 'Ctrl+Shift+M',
  },
  ctxTarget: null,
  termHistory: [], termHistoryIdx: -1,
  findMatches: [], findIdx: 0,
  findCase: false, findRegex: false, findReplaceOpen: false,
  modalAction: null,
  quickSelectedIdx: 0,
  previewDebounce: null,
  currentViewport: 'full',
  recentProjects: [],
  extensions: [
    { id: 'theme-support', name: 'Theme Support', desc: 'Multiple themes', installed: true, category: 'UI' },
    { id: 'terminal', name: 'Built-in Terminal', desc: 'Terminal panel', installed: true, category: 'Tools' },
    { id: 'syntax-highlighting', name: 'Syntax Highlighting', desc: 'Language-aware highlighting', installed: true, category: 'Editor' },
    { id: 'mini-map', name: 'Minimap', desc: 'Code overview overlay', installed: true, category: 'Editor' },
    { id: 'git-ux', name: 'Git UX', desc: 'Branch and merge tools', installed: true, category: 'Source Control' },
    { id: 'workspace-sync', name: 'LightningFS Sync', desc: 'Bidirectional workspace watcher', installed: true, category: 'Workspace' },
  ],
  gitState: {
    branch: 'main',
    branches: ['main', 'feature/preview'],
    mergeTarget: 'main',
    staged: [],
    changed: [],
  },
  grammarRegistry: {},
  workspaceSync: null,
  db: null,
};
